version: '3.8'

services:
  django:
    build: ./backend
    container_name: django
    env_file:
      - .env
    networks:
      - app
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    depends_on:
      - postgres
      - redis
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./frontend:/frontend
    networks:
      - app
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app
    restart: always

  redis:
    image: redis:6
    container_name: redis
    networks:
      - app
    restart: always

networks:
  app:
    driver: bridge