version: '3.8'

services:
  django:
    build: ./backend/app
    container_name: django
    env_file:
      - .env
    ports:
      - "8000"
    networks:
      - app
    volumes:
      - ./backend/app:/app
      - ./frontend:/frontend
    depends_on:
      - postgres
      - redis
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - app
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database/data:/var/lib/postgresql/data
    networks:
      - app
    restart: always

    redis:
      image: redis:6
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - app
      restart: always

networks:
  app:
    driver: bridge