# Generated by Django 5.1.2 on 2024-11-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_friend_unique_together_remove_friend_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='EN'),
        ),
    ]
