# Generated by Django 5.1.2 on 2024-11-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='defeat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='win',
        ),
    ]
