# Generated by Django 5.1.2 on 2024-11-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customuser_defeat_remove_customuser_win'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
