# Generated by Django 5.1.2 on 2024-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_game_match_user3_match_user3_score_match_user4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.CharField(default='pong_1v1'),
        ),
    ]
