# Generated by Django 5.1.2 on 2024-11-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user3_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user4_score',
        ),
    ]
