# Generated by Django 5.1.2 on 2024-11-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_match_user3_score_remove_match_user4_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user4',
        ),
    ]
