# Generated by Django 5.1.2 on 2024-11-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_match_mode_alter_match_user1_alter_match_user2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='mode',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='matchs',
            old_name='mode',
            new_name='game',
        ),
    ]
