# Generated by Django 5.1.2 on 2024-11-14 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_match_options_alter_matchs_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_position', models.IntegerField(default=4)),
                ('user2_position', models.IntegerField(default=4)),
                ('user3_position', models.IntegerField(default=4)),
                ('user4_position', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_first_opponents_1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_second_opponents_1', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_first_opponents_2', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_second_opponents_2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_winner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament 1v1v1v1',
                'verbose_name_plural': 'Tournaments 1v1v1v1',
                'ordering': ['-created_at'],
            },
        ),
    ]
