# Generated by Django 5.1.2 on 2024-11-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchs',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='user4',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user4',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Matchs',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
