# Generated by Django 5.1.2 on 2024-11-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
