# Generated by Django 5.1.2 on 2024-11-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_messages_friend_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='Blocked',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
